### ISSUE TITLE
GCC Library Dependencies

### ISSUE THREAD

**Issue by kprinssu** [psp2dev/psp2lib#3]
I am currently on OSX, and I was getting build errors with gcc cross-compiler (when I ran autogen.sh).

The specific error was:

```
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
ftp://gcc.gnu.org/pub/gcc/infrastructure/.  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
```

It is clear that libraries: gmp, mpfr, and mpc were not present on my system. The fix was to  install the missing libraries via Homebrew (http://brew.sh/):

```
brew install gmp
brew install mpfr
brew install mpc
```

Then I edited autogen.sh to add the proper flags:

```
echo Running gcc/configure
(cd gcc; ../../gcc/configure --disable-libstdcxx-verbose --enable-languages=c,c++,lto --with-gmp=/usr/local/Cellar/gmp/6.0.0a --with-mpfr=/usr/local/Cellar/mpfr/3.1.2-p11 --with-mpc=/usr/local/Cellar/libmpc/1.0.3 --with-newlib --with-cpu=cortex-a9 --with-fpu=neon-fp16 --target=arm-none-eabi "$@")
echo Done running gcc/configure
```

Obviously, this is not viable since you will have to continuously keep changing autogen.sh for each update of psp2lib. This error may also effect other operating systems as well. 

The end-user to properly setup their development environment (and this information should be added to the wiki?). Or, the other option is to make the autogen script "smarter" by automatically resoling the dependencies for gcc.  If this is a non-issue, please feel to close this "issue".

**Comment by 173210** [comment]
Usually (Ubuntu 15.04 is usual in my world), you don't have to edit autogen.sh. Well, writes about dependencies on wiki should make sense.

**Comment by kprinssu** [comment]
I have more OSX related fixes to get GCC compiled, is there a style guide for the wiki?

I can easily write up the necessary information for the wiki.

**Comment by 173210** [comment]
No. For now, see the existing code and write as it is.
Anyway, thank you for your contribution!

**Comment by psxdev** [comment]
Advice use   ./contrib/download_prerequisites inside gcc package. It will download stuff related to gmp, mpfr, etc. Right version for gcc version that you want to compile in the right place. No need to install extra stuff

For OS X i use my repo https://github.com/psxdev/psp2toolchain, problem with depth bracked fixed with configure options

I like more to separate gcc toolchain and lib related to it from  psp2 specific libs

**Comment by 173210** [comment]
Travis CI and I download them from apt repository. It's mich easier for Ubuntu users ;)

**Comment by kprinssu** [comment]
The new way of compiling psp2sdk is much easier, and I am not getting the dependency errors.
